name: pandas
channels:
  - anaconda
  - defaults
dependencies:
  - python=3.5.6
  - pip
  - pip:
    - pip==20.3.4
    - pandas==0.24
    - numpy==1.15
    - pycodestyle==2.4
    - matplotlib
    - Pillow
